---@diagnostic disable
local State = require('motioncoach-nvim.state')

describe('state.lua', function()
  it('get returns runtimeState table', function()
    local state = State.get()
    assert.is_table(state)
    assert(state.namespace ~= nil)
    assert(state.keyRingBuffer ~= nil)
  end)
  it('get_or_create_per_buffer returns buffer state', function()
    local buf = State.get_or_create_per_buffer(123)
    assert.is_table(buf)
    assert(buf.yankRing ~= nil)
    assert(buf.evidenceCounters ~= nil)
    assert(buf.hotspotVisitCountsByPositionKey ~= nil)
  end)
  it('get_or_create_per_buffer returns same object for same buffer', function()
    local buf1 = State.get_or_create_per_buffer(1)
    local buf2 = State.get_or_create_per_buffer(1)
    assert.are.equal(buf1, buf2)
  end)
end)
