local Utils = require('motioncoach-nvim.utils')

describe('utils.lua', function()
  it('clampNumber returns min if value is less', function()
    assert.are.equal(Utils.clampNumber(1, 5, 10), 5)
  end)
  it('clampNumber returns max if value is more', function()
    assert.are.equal(Utils.clampNumber(15, 5, 10), 10)
  end)
  it('clampNumber returns value if in range', function()
    assert.are.equal(Utils.clampNumber(8, 5, 10), 8)
  end)
  it('now_ms returns a positive integer', function()
    local ms = Utils.now_ms()
    assert.are.equal(type(ms), 'number')
    assert(ms > 0)
  end)
end)
