-- nvim --headless -c "PlenaryBustedDirectory spec/" 2>&1 | tee test-log.txt

--  TODO: may not need these functions in this module... only need it if we going to send Homie his keystrokes.
--
-- local function build_key_string(keys)
--   return ' ' .. table.concat(keys, ' ') .. ' '
-- end
--
-- local function has_any_key(keys, keySet) --- Do it have keys??
--   for _, k in ipairs(keys) do
--     if keySet[k] then
--       return true
--     end
--   end
--   return false
-- end
--
-- ---@function --turns concurrent keys into single string.  example: `h`,`h`,`h`,`h` ~ `4h`
-- ---@return string | nil
-- local function count_compression(keys)
--   local allowed = { j = true, k = true, h = true, l = true, w = true, b = true, e = true }
--   local lastToken, repeatCount = nil, 0
--
--   for _, token in ipairs(keys) do
--     if allowed[token] then
--       if token == lastToken then
--         repeatCount = repeatCount + 1
--       else
--         lastToken, repeatCount = token, 1
--       end
--     else
--       lastToken, repeatCount = nil, 0
--     end
--   end
--
--   if lastToken and repeatCount >= 5 then
--     return ('You pressed `%s` %d times. Try `%d%s` (count + motion).'):format(
--       lastToken,
--       repeatCount,
--       repeatCount,
--       lastToken
--     )
--   end
--   return nil
-- end
