name: Neovim Plugin Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Neovim
        run: sudo apt-get install -y neovim
      - name: Install Plenary.nvim
        run: git clone --depth=1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/test/start/plenary.nvim

      - name: Neovim Version
        run: nvim --version

      - name: List Test Files
        run: ls -R spec

      - name: Run Plenary Tests
        run: |
          set -o pipefail
          nvim --headless -c "PlenaryBustedDirectory spec/" 2>&1 | tee test-log.txt

      - name: Show Test Log Output
        if: always()
        run: cat test-log.txt

      - name: Upload Test Log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-log
          path: test-log.txt

